### ISSUE TITLE
JEI recipe view conflict

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [blay09/CraftingTweaks#101]
While it certain GUIs (furnace and chest) I am unable to view recipes or uses for items while crafting tweaks is installed.

**Comment by BlayTheNinth** [comment]
Version?

**Comment by awkwaRdcaRRot** [comment]
Sorry, definitely should have included these details first. Minecraft 1.11.2, the last couple versions of JEI, latest crafting tweaks, and forge 2285 (not sure if the newer versions of forge fix the issue or not, i took crafting tweaks out of my pack for now).

**Comment by SeriousCreeper** [comment]
Having the same issue, tested with forge 2282 and JEI version 4.3.4.273.

Version 7.1.7 of Crafting Tweaks doesn't display recipes when pressing the R key in JEI, even if i remove the shortcut for Crafting Tweaks rotating grid. 
Version 7.1.6 works fine.
