### ISSUE TITLE
Portable Crafting Table GUI Issues

### ISSUE THREAD

**Issue by ChloeDawn** [blay09/CraftingTweaks#106]
Portable Crafting Table GUI's are not overriding `drawDefaultBackground()` and `renderHoveredToolTip()`.

See https://github.com/copygirl/WearableBackpacks/pull/33 for reference.

**Mod version:** [8.1.4](https://minecraft.curseforge.com/projects/crafting-tweaks/files/2457095)
**Forge version:** [1.12-14.21.1.2426](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2426/forge-1.12-14.21.1.2426-changelog.txt)

**Comment by BlayTheNinth** [comment]
Fixed in https://github.com/blay09/CraftingCraft/commit/8575aeb7a35e6345ca5d0b4d48a1152c47b4caa5

**Comment by ChloeDawn** [comment]
Ooops, sorry, I got the repos mixed up lmao
