### ISSUE TITLE
[1.12.1] Incompatibility with RFTools Control Workbench.

### ISSUE THREAD

**Issue by VT-14** [blay09/CraftingTweaks#110]
Issue: 
When Crafting Tweaks is installed, the RFTools Control Workbench crashes when items are inserted into it.  Both manual insertion and vanilla Hoppers cause a crash.

Inserting using RFTools Control will return an "Invalid Inventory" error.  Nothing happens (no crash).

Tested in Single Player with only RFTools Control, Crafting Tweaks, JEI, and required mods (McJtyLib and RFTools).

Minecraft: 1.12.1
Forge: 14.22.0.2474
RFTools Control: 1.6.8
Crafting Tweaks: 8.1.5

Manual Insertion Crash Log: https://gist.github.com/VT-14/1f7be2b8e5ea2bca8b723d2e8c95621e

Hopper Insertion Crash Log: https://gist.github.com/VT-14/64669a8a42a40755b5bb3027b5d0849d

RFTools Control Issue: McJty/RFToolsControl#110

**Comment by BlayTheNinth** [comment]
Fairly certain this has nothing to do with Crafting Tweaks. Crafting Tweaks only touches the GUI and Container (definitely not the tile), and it only does so for mod GUIs that are actually supported (RFTools from what I know is not one of those), and it only does non-intrusive changes like adding buttons and moving items (and that only when you actually click one of the buttons).

Looking at RFToolsControl code, it's [simply missing a null-check](https://github.com/McJty/RFToolsControl/blob/1.12/src/main/java/mcjty/rftoolscontrol/blocks/workbench/WorkbenchTileEntity.java#L95) as `findMatchingRecipe` is `@Nullable`.
