### ISSUE TITLE
Ender chest/Pouch problem - in the Direwolf20 1.12.2.

### ISSUE THREAD

**Issue by Uginsecond** [blay09/CraftingTweaks#112]
Hey!
I installed a new Direwolf20 pack 1.10 and added "Crafting Tweaks_1.12.1-8.1.6.jar" .
After this I got a problem : losing items, sent after mining in the Aroma1997`s Mining world, - 99% was lost on the way. Sent over a Ender pouch to the Ender chest (same color - white). After this - a Ender pouch sent items then you near a Ender chest only.
After I remove a mod - seems all back, but no solution was found. Still something in the saved game, that kill normal working of this pair, Ender chest-Pouch.
For a experiment I got a clean install of pack (1.20) and create a new world - all work perfect!
But after I added a old save - still same problem.

**Comment by BlayTheNinth** [comment]
Crafting Tweaks only ever does anything on user actions (that is, clicking the crafting buttons or hotkeys). It's impossible for it to interfere with Ender Chest item synchronization. You were most likely experiencing an issue unrelated to this mod. If you can provide detailed steps to reproduce this issue I can take another look, but I highly doubt Crafting Tweaks has anything to do with it.

**Comment by Uginsecond** [comment]
Hey!
I was surprised too, but I do only one change to the modpack - added "Crafting Tweaks_1.12.1-8.1.6.jar".
No any config changes.
Home LAN, Cable, server work on system with 16Gb memory, only me on server.
Base chunk-loaded by Ftbutils , all worked perfect. At least I seen all work as need, most of the time I use "Aroma1997`s Mining world" for farming food/trees too.
So - I don`t know who and how...
Anyway, I deleted all old game saves/server files - so - nothing to do.
