### ISSUE TITLE
[1.12.2] [Compatibility issue] Your mod break the craft from Astral Sorcery, CraftingTable with crystal light

### ISSUE THREAD

**Issue by Fireztonez** [blay09/CraftingTweaks#115]
When you place, in a big Astral Sorcery Temple with a Floating crystal, and try to craft Resonating Wand or Luminous Crafting Table, it doesn't work when your mod is install. I just remove CraftingTweaks and is start working...

I Like the utility button of your mod, so I want to be able to have in my modpack....
Can you please look to fix that compatibility issue

Minecraft: 1.12.2
CraftingTweaks 1.12.1-8.1.6
Forge 14.23.2.2627
AstralSorcery 1.12.2-1.8.5

Thank's

**Comment by BlayTheNinth** [comment]
Need steps to reproduce (for someone who does not know Astral Sorcery) and logs occuring at the time of opening the crafting table or when the "doesn't work" happens. 

It's also quite unlikely it's actually Crafting Tweaks causing this issue, as it doesn't meddle with the Luminous Crafting Table at all. This is most likely an issue unrelated to this mod, and the fact it started working after removing Crafting Tweaks is probably a coincidence. Let me know if you can consistently reproduce the issue.

**Comment by Fireztonez** [comment]
This is for sure not a coinsidence, I try that multiple time, with your mod and without.

The way to reproduce is realy easy, you install Astral Sorcery, you found a big Temple (Found habitually in a Mountain Biome), in the cave of the structure you have a Floating Crystral... You put a Vanilla Crafting table beside and you can see Light Beam going to the Crafting Table. Now you can try to craft the thing from Astral Sorcery you whant, like indicate in the  Astral Sorcery Book...

If you whant, I can make you a short video to show you when I hjave more time...

**Comment by BlayTheNinth** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/588
https://github.com/HellFirePvP/AstralSorcery/issues/535

The reason it started working after removing Crafting Tweaks is because it involved restarting Minecraft. This is an issue on Astral Sorcery's side and has nothing to do with Crafting Tweaks.
