### ISSUE TITLE
PrimalCore Support

### ISSUE THREAD

**Issue by alxcool** [blay09/CraftingTweaks#118]
Hi! I really like your mods and your dedication to it!
I was reading this mod page on forge and there is a mod I would like to suggest to include compatibility for : Primal Core / Forgecraft. https://minecraft.curseforge.com/projects/primalcore.

They have 2 crafting tables
Primal:worktable_slab variation 0 to 9
and
Primal:worktable_shelf variation 0 to 9
thk!

**Comment by BlayTheNinth** [comment]
Closing since PrimalCore has not been updated past Minecraft 1.12.
