### ISSUE TITLE
Artisan Worktables Mod Support

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CraftingTweaks#120]
Support should be PRed to Artisan Worktables using the IMC API. Preferably 1.14+.

**Comment by codetaylor** [comment]
Complete: https://github.com/codetaylor/artisan-worktables/issues/80

**Comment by codetaylor** [comment]
Also, I wasn't able to connect to your maven or jenkins. Just a heads up that they might be down or unreachable.

**Comment by BlayTheNinth** [comment]
Nice! Maybe I should look into allowing custom button textures so they could better match the custom UI (assuming that isn't just a texture pack).

I've shut down my Jenkins and Maven since with Curse Maven / flatDir repos I didn't see as much of a need anymore.

**Comment by hron84** [comment]
@blay09 jenkins could be still helpful for reaching nightly releases / testing building issues...
