### ISSUE TITLE
Could not register Crafting Tweaks addon for progressiveautomation - internal names have changed.

### ISSUE THREAD

**Issue by C0rn3j** [blay09/CraftingTweaks#124]
```
forge-1.12.2-14.23.5.2838
CraftingTweaks_1.12.2-8.1.9.jar
ProgressiveAutomation-1.12.2-1.7.8.jar
```

**Comment by BlayTheNinth** [comment]
The special compat for Progressive Automation has been removed from Crafting Tweaks for 1.14, if Progressive Automation updates we can look into PRing IMC support to them to keep it more stable.
