### ISSUE TITLE
Ae2 Crafting terminal

### ISSUE THREAD

**Issue by unknownSold** [blay09/CraftingTweaks#125]
Please add support for Ae2 in 1.12.2

**Comment by Skydragonsz** [comment]
From https://blay09.gitlab.io/mod-docs/#/faq

> Can I connect an Applied Energistics/Refined Storage network to my kitchen?
> * No, and it is very unlikely to ever happen.

**Comment by BlayTheNinth** [comment]
Duplicate of #98
