### ISSUE TITLE
Compatibility Request for 1.14 Mod.

### ISSUE THREAD

**Issue by Wissi** [blay09/CraftingTweaks#126]
Awesome mod we love your work and use it in all our modpacks.

We are updating our modpacks to 1.14.4 and it seems you mod is not working with [Crafting Station](https://www.curseforge.com/minecraft/mc-mods/crafting-station) mod yet.

Could you code a compatibility w/this crafting table, please?
Using:
Forge-28.0.81.jar
craftingstation-2.0.2a.jar
CraftingTweaks_1.14.4-10.1.3.jar

Thank you so much.

**Comment by Tfarcenim** [comment]
I tried, but none of the information I found was 1.13+ and even the readme is outdated.

**Comment by gabriel-andreescu** [comment]
I've made a pull request for Crafting Station, maybe when @Tfarcenim has some time, he will merge it.

**Comment by BlayTheNinth** [comment]
Thanks for the PR. I've also updated the README for the latest version.
