### ISSUE TITLE
*Idea* as currently there are no other mod on 1.14.4 that does this.

### ISSUE THREAD

**Issue by RepoDraghon** [blay09/CraftingTweaks#128]
How difficult would it be to add the ability to Shift+click on an item in inventory to go straight to the crafting grid? I believe either Inventory or Mouse Tweaks adds this ability but they are yet to be upgraded. I was thinking that maybe (I don't know since I don't code) that it might be a simple code that adds this feature but then turns off as to not conflict with other mods that introduce the ability...

No rush, just wondering...

**Comment by BlayTheNinth** [comment]
You can press W (or whatever is your up key) and click the item to move it to the crafting grid.

**Comment by RepoDraghon** [comment]
Then the answer is easy, doesn't matter what key it is, but thanks, now I know. Shift would be easier as that is what it was back in 1.12.2 but it probably wasn't this mod that added that button...

**Comment by BlayTheNinth** [comment]
W-Click is the Vanilla way of moving stuff to your inventory crafting slots which Crafting Tweaks expands to other crafting tables. Shift-click would conflict with the normal hotbar-to-inventory-to-container transfer.
