### ISSUE TITLE
I Like Wood Support

### ISSUE THREAD

**Issue by sepsol** [blay09/CraftingTweaks#130]
1. [Crafting Station](https://www.curseforge.com/minecraft/mc-mods/crafting-station)
2. [I Like Wood](https://www.curseforge.com/minecraft/mc-mods/i-like-wood)

**Comment by BlayTheNinth** [comment]
Crafting Station support was added in the latest version of Crafting Station.

**Comment by BlayTheNinth** [comment]
Looks like I Like Wood already supports Crafting Tweaks.
