### ISSUE TITLE
Balance/Spread Grid not working in FastWorkbench

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/CraftingTweaks#133]
The Balance/Spread Grid buttons do nothing in a Crafting Table from the FastWorkbench mod. 
Clear and Rotate work just fine.

#### Version
- CraftingTweaks_1.14.4-10.1.4

**Comment by BlayTheNinth** [comment]
Does it work with FastWorkbench-1.14.4-2.1.3.jar?

Duplicate of #127

**Comment by NielsPilgaard** [comment]
Sorry about that. No it does not. Closing as duplicate.
