### ISSUE TITLE
[1.14] Crash on launch

### ISSUE THREAD

**Issue by IronPiston** [blay09/CraftingTweaks#138]
Crafting Tweaks Version: 10.1.5
Forge Version: 28.1.109

After applying a resource pack, the game crashed and continues to crash on launch. Removing the resource pack doesn't fix this issue. I have narrowed it down specifically to Crafting Tweaks, the game launches correctly without it. 

[Log](https://paste.ee/p/zR1GJ)

**Comment by BlayTheNinth** [comment]
The config file got corrupted, you'll have to delete the craftingtweaks-client.toml file in order to launch with CraftingTweaks again (and update to the latest version so it won't corrupt again).
