### ISSUE TITLE
Button hiding feature doesn't work correctly

### ISSUE THREAD

**Issue by Greg-21** [blay09/CraftingTweaks#139]
The button hiding feature is supposed, I think, to hide (or show) the 3 buttons that are added by this mod, and then move the Minecraft recipe book button from the top-right corner to the left of the crafting grid (or vice versa) in the crafting table GUI. But it doesn't work as it should.

In older versions of this mod this feature hides the 3 "grid" buttons and does nothing with the recipe book button, and then, once you reopen the crafting table GUI, the recipe book button is where it should be (to the left of the crafting grid), but the 3 "grid" buttons are displayed again (look at the screenshot below).

In newer versions of this mod (for Minecraft 1.14.4) the button hiding feature moves the recipe book button, and then it simply does nothing more, which results in a situation like this:
![Crafting-Tweaks-buttons-cover-recipe-book-button](https://user-images.githubusercontent.com/34160838/72540917-e7da4700-3881-11ea-960c-38cd6a5414ae.png)

I was able to reproduce this issue on the following configurations (I didn't test other configs):
* Minecraft versions: 1.14.4, 1.12.2
* Crafting Tweaks versions: 10.2.0, 8.1.9
* Forge versions: 28.1.115, 14.23.5.2768

**Comment by Greg-21** [comment]
Thank you for the fix, I'll check it out as soon as you release the next mod version. In the meanwhile I'd like to ask you whether you still support Minecraft 1.12.2, or maybe you simply moved all your focus to 1.14.4?

**Comment by BlayTheNinth** [comment]
1.12 is only getting critical fixes at this point.

**Comment by Greg-21** [comment]
OK, fine then.
