### ISSUE TITLE
Multiple crashes after updating to Forge 32.0.66

### ISSUE THREAD

**Issue by thrice0** [blay09/CraftingTweaks#146]
Multiple crashes appear using the crafting table after i updated to Forge 32.0.66

https://pastebin.com/xxtzDsfm

**Comment by Trostmm** [comment]
Can confirm, Noticed same issue w/ plain install w/ just forge 32.0.66 and CraftingTweaks_1.16.1-12.0.3.
Can replicate by placing crafting table and hitting any of the buttons.
