### ISSUE TITLE
Idea Request integrate what "stimmedcow : NoMoreRecipeConflict" does

### ISSUE THREAD

**Issue by RepoDraghon** [blay09/CraftingTweaks#150]
The project stimmedcow : NoMoreRecipeConflict shows that it has been abandoned. I was hoping someone would pick it up and bring it into the new versions of Minecraft. I thought that this mod of yours would be the perfect platform to host this feature as your mod already has to do with the Crafting table...

If you don't know what the mod does, it allows you to literally select what mod you want the finished product to be from, so for instance, if you wanted a block of copper from Mekanism but the crafting bench only shows from Thermal, it adds a button to select the next mod.

**Comment by BlayTheNinth** [comment]
Out of scope for Crafting Tweaks, Crafting Tweaks adds QOL tweaks and doesn't override the crafting handling in the backend.
