### ISSUE TITLE
Vanilla recipe book not "unhiding" 

### ISSUE THREAD

**Issue by emprenex13** [blay09/CraftingTweaks#152]
hi i am trying to unhide the vanilla recipe book and using the mod options button and changing the config file has not changed it. i am playing the limitless 3 pack.

thanks

**Comment by BlayTheNinth** [comment]
Crafting Tweaks by default only moves the button, and only hides the button if hiding the button is enabled.

You probably have some other mod that's hiding it. Crafting Tweaks doesn't try to "unhide" the button if something else is hiding it.
