### ISSUE TITLE
Right click to craft a single stack not working in 1.16.5 modpack

### ISSUE THREAD

**Issue by Boerny41** [blay09/CraftingTweaks#157]
### Minecraft Version

1.16

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### Mod Version

CraftingTweaks_1.16.5-12.2.1.jar

### Describe the Issue

The "Right-click the result slot to craft a full stack" is not working. Neither with vanilla nor other crafting tables. 

I can only say that it does not work in Stacia Expert and I can't tell if the pack devs messed something up or if there is a problem with this mod.

**Comment by BlayTheNinth** [comment]
Does it happen with only Crafting Tweaks installed?
