### ISSUE TITLE
Crash + Data Corruption with Antique Atlas

### ISSUE THREAD

**Issue by foul-fortune-feline** [blay09/CraftingTweaks#158]
### Minecraft Version

1.17

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### Mod Version

13.0.0+0

### Describe the Issue

When opening the Antique Atlas gui using right click, crafting tweaks crashes the game and corrupts the player data. The version of Antique Atlas is 6.1.0-fabric-mc1.17.1, just in case that's somehow relevant.

### Logs

https://paste.ee/p/rd6Y2

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Normally I use sodium, but not for the report submitted

**Comment by BlayTheNinth** [comment]
Paste expired

**Comment by Zano1999** [comment]
> Paste expired

I have the same issue, here the crash report: https://pastebin.com/ZsthjAJ1
