### ISSUE TITLE
Engineer's Hammer Not Crafting After Durability lower than 100

### ISSUE THREAD

**Issue by leonardostorrespro** [blay09/CraftingTweaks#159]
### Minecraft Version

1.16

### Mod Loader

Forge

### Mod Loader Version

36.2.6

### Mod Version

12.2.1

### Describe the Issue

Whenever the Engineer's Hammer is used and the durability is reduced by even one, it stops it from crafting any more recipes.

I attempted with Iron Sheets from Valhelsia 3- 3.4.3 modpack.

![Crafting Player inventory](https://user-images.githubusercontent.com/85841138/136812570-98c8f4c1-07f0-455f-85e7-2b01d56f0b09.png)
![Crafting Table No](https://user-images.githubusercontent.com/85841138/136812573-43c06986-cd90-484c-8cd0-27c72d1d72aa.png)
![Crafting Table Yes](https://user-images.githubusercontent.com/85841138/136812574-f0743cb8-9a42-486c-84aa-1c3fcfd79599.png)
![Not crafting Player inventory](https://user-images.githubusercontent.com/85841138/136812576-f6166266-b718-4a2d-8de0-6d2596743e1b.png)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine and Spark

**Comment by BlayTheNinth** [comment]
Have you tested without Crafting Tweaks?

**Comment by leonardostorrespro** [comment]
> Have you tested without Crafting Tweaks?

Good call. Just finished testing that and the problem remains so, the issue, does not really in Crafting Tweaks. My bad, apologies!
