### ISSUE TITLE
1.17.1 crash, I'm sure it's not on your end but maybe you can look into it.

### ISSUE THREAD

**Issue by RepoDraghon** [blay09/CraftingTweaks#160]
### Minecraft Version

1.17

### Mod Loader

Forge

### Mod Loader Version

37.0.103

### Mod Version

13.0.0+0

### Describe the Issue

Issue is described here: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/265 however the issue is that this mod is causing Sophisticated Backpacks to error out while loading just before the title screen.

**Comment by BlayTheNinth** [comment]
Seems to be caused by outdated integration code on Sophisticated Backpack's side.
