### ISSUE TITLE
Crafting Tweaks / Balm crash on 1.18 Fabric

### ISSUE THREAD

**Issue by itsdinkd** [blay09/CraftingTweaks#162]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.12.8

### Mod Version

13.0.0

### Describe the Issue

Balm 2.1.1

Saw my server crashed, this is the crash log. Oddly it was a server crash and not player.

### Logs

https://pastebin.com/HDDpTtiK

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Lithium

**Comment by BlayTheNinth** [comment]
Can't reproduce, this might be an issue with your Fabric install
