### ISSUE TITLE
【forge 1.18.1/1.16.5】Incompatibillity with inventorio

### ISSUE THREAD

**Issue by AmyRose1288** [blay09/CraftingTweaks#164]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.20

### Mod Version

12.2.1

### Describe the Issue

![image](https://user-images.githubusercontent.com/19208524/151057105-e2f4aa1b-c27e-4157-90a5-003d276ab9a3.png)
while using inventorio,inventory profile next (fixed incompatibillity)and CraftTweaker,UI is messed up

### Logs

N/A (beacuse it's not a crash)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

OptiFine,Inventory Profile Next,Inventorio

**Comment by BlayTheNinth** [comment]
The screenshot shows nothing from Crafting Tweaks. Crafting Tweaks adds buttons to crafting tables, it doesn't change the inventory
