### ISSUE TITLE
[1.18.2] Buttons not showing up in sophisticated backpacks crafting upgrade gui.

### ISSUE THREAD

**Issue by Baggytrousers27** [blay09/CraftingTweaks#166]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.41

### Mod Version

craftingtweaks-forge-1.18.1-14.0.2

### Describe the Issue

Forge 1.18.1 39.0.75
balm-2.4.3+0
craftingtweaks-forge-1.18.1-14.0.2
sophisticatedbackpacks-1.18.1-3.15.9.533
![2022-04-07_13 29 18](https://user-images.githubusercontent.com/15883796/162115126-20b130d7-a937-4b3d-a7dc-2806b8d9a8a8.png)

Forge 1.18.2 40.0.41
balm-3.0.2+0
craftingtweaks-forge-1.18.1-14.0.2 (Listed for 1.18.2 on curseforge)
sophisticatedbackpacks-1.18.2-3.15.17.559
![2022-04-07_13 37 05](https://user-images.githubusercontent.com/15883796/162115578-9c0e5803-39c5-4f3c-98cc-47f896da7f72.png)

### Logs

Standard https://pastebin.com/Wtgd4FWT Debug https://pastebin.com/6ED4Jj77

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
This support was done on Sophisticated Backpacks side and probably removed / disabled from there.

**Comment by Baggytrousers27** [comment]
Has since been remedied. Cheers.
