### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [blay09/CraftingTweaks#173]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.60

### Mod Version

craftingtweaks-forge-1.18.2-14.0.3.jar

### Describe the Issue

https://paste.gg/p/anonymous/0afe9ee75a2d46e2bfffdde92955d230

**Comment by BlayTheNinth** [comment]
Does this happen with only Crafting Tweaks installed?
