### ISSUE TITLE
"Inflate Data is Bad" on connecting to certain servers

### ISSUE THREAD

**Issue by nickkeane** [blay09/CraftingTweaks#174]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Mod Version

15.1.0

### Describe the Issue

When joining certain public servers like mc.vortexnetwork.net, an exception occurs repeatedly:

Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad

Playing on ComplexMCs SMP servers gives a similar result

### Logs

https://pastebin.com/BjsiP00w

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Lithium, Sodium, Phosphor

**Comment by BlayTheNinth** [comment]
Clarify with those servers whether the mod is allowed, this is most likely their server blocking the mod. Crafting Tweaks is not listed on https://vortex-games.notion.site/Game-Modifications-0eb005b4a5644cabbba3e3ce66c91d70, for example.

**Comment by ZakirKhanSecE** [comment]
Im having this same issue but for a private server

![Image](https://github.com/user-attachments/assets/0f3ae5c2-e47b-4468-8993-a49e2f447d98)
![Image](https://github.com/user-attachments/assets/60dc8205-6b91-4f5f-b359-d362b548cd65)
And then my cpu crashes

**Comment by orfn4** [comment]
im having this exact issue on a modpack, same 2 codes being shown,. was there a resolution that people found? i see a mismatched mod may cause it? all mods on server and my end should be the same though i can play then randomly crash

**Comment by Nico-1028** [comment]
I'm having the same exact issue. Anyone get the fix?
