### ISSUE TITLE
Fabric 1.18.2 Server crashes when loading CraftingTweaks

### ISSUE THREAD

**Issue by Whattheblah12** [blay09/CraftingTweaks#175]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Mod Version

1.18.2-14.0.3

### Describe the Issue

My server was working like a week ago but i stopped running it and i come back today to find it crashes, it blames this mod and goblin traders, so i tried running the server with this mod alone and the crash is repeatable\
IT IS IMPORTANT TO NOTE THE MOD WORKS FINE ON SINGLEPLAYER, JUST LOCAL HOSTING THE SERVER WILL CRASH
1) newest version of fabric for 1.18.2 server
2)install crafting tweaks and dependencies
3) run the server
4) crashes and blames craftingtweaks

### Logs

https://pastebin.com/uDaCBzw2

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by BlayTheNinth** [comment]
Something is wrong with your config file: `Key is not followed by an equals sign on line 1`
