### ISSUE TITLE
Can't build Gradle won't compile api

### ISSUE THREAD

**Issue by sshShadowLinuxCreator** [blay09/CraftingTweaks#186]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.85

### Mod Version

14.0.3

### Describe the Issue

Could not find method compile() for arguments [curse.maven:craftingtweaks-233071:3830906] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by BlayTheNinth** [comment]
Sounds like your gradle version might be too new. Are you using the gradle wrapper (`./gradlew` instead of `gradle`)?

**Comment by sshShadowLinuxCreator** [comment]
No just using the build.gradle file in intellij
