### ISSUE TITLE
Missing Buttons using Crafting Station mod

### ISSUE THREAD

**Issue by ClaudiusMinimus** [blay09/CraftingTweaks#190]
### Minecraft Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Mod Version

1.19-15.1.0

### Describe the Issue

The Balance Grid and Clear Grid buttons are missing, and the Rotating Grid button has the Clear Grid icon as shown in the clip while pressing the button.
 - craftingtweaks-forge-1.19-15.1.0.jar
 - craftingstation-1.19.2-6.jar
 
![craftingStation](https://user-images.githubusercontent.com/17887664/210110340-6a3acc0a-5b64-4432-a453-a65aad468fd2.gif)
[latest.log](https://github.com/TwelveIterationMods/CraftingTweaks/files/10326227/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by Nijoma69** [comment]
Same in 1.19.3 version
