### ISSUE TITLE
Keybinds block other input even if context is not met

### ISSUE THREAD

**Issue by DemonSlayer112** [blay09/CraftingTweaks#191]
Hello! Love the mod, and it makes crafting much more relaxing on the modpacks im making.
However, i noticed a small issue.
You see im trying to limit shortcuts to the left side of the keyboard for easier in-game action.

However, for some reason this disables other keys.
For example, i use "C" to open my crafting table from another mod.
However, assigning "C" to Compress ALL disables this which i find weird, feels like this should work only when a crafting gui is already up, right?
Same for S, it disables me walking backwards :(
Can we be given some sort of option to choose which gui there active in or just enable only on crafting gui?

Would be greatly appreciated as an config option if these commands have _any_ functionality outside the crafting table.
Fabric - 1.19.2

**Comment by BlayTheNinth** [comment]
Fixed in Balm 4.6+
