### ISSUE TITLE
rightClickCraftsStack dupe

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CraftingTweaks#203]
I dont know if its related but a stack of a crafted item can be obtained even if not enough base material (at least items for one output are required) by right clicking on output stack when "rightClickCraftsStack"config is "true". This is happening on recent versions of FTB ONE. See:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3449

_Originally posted by @piedrrum in https://github.com/TwelveIterationMods/CraftingTweaks/issues/202#issuecomment-1654770032_

**Comment by BlayTheNinth** [comment]
Cannot reproduce

**Comment by piedrrum** [comment]
It was a compatibilty issue with fastworkbench, I reproduced:
![image](https://github.com/TwelveIterationMods/CraftingTweaks/assets/60243235/74d2a86f-bd80-4148-a2ef-ba1039a2a1aa)

I tested with new versions of fastworkbench and this was fixed.
