### ISSUE TITLE
Crash When Refilling last craft in a Sophisticated Backpack with Crafting Upgrade

### ISSUE THREAD

**Issue by djnifos** [blay09/CraftingTweaks#210]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.19

### Mod Version

1.20-18.2.2.jar

### Balm Version

1.20.1-7.2.1.jar

### Describe the Issue

I used a netherite backpack with a crafting upgrade and crafted prudentium using a master infusion crystal.   Craft one, tab to refill, crash. Originally reported in AllTheMods 9.  Reproduceable with the mods shown in the picture.   
![image](https://github.com/TwelveIterationMods/CraftingTweaks/assets/2243466/c4eda41b-eeff-4894-a582-dea4e83e5708)
https://gist.github.com/djnifos/9f4965d9c7892508443a5d1c6b632b37

### Logs

https://gist.github.com/djnifos/76ca82e5917cb91bab2660fc445a1d44

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by BlayTheNinth** [comment]
The latest 1.20.1 and 1.20.4 versions should no longer crash and will instead refuse to refill the grid in this case. A future 1.20.4 version will add API support for custom refill logic so that this functionality can be reinstated then.
