### ISSUE TITLE
Log spam clicking

### ISSUE THREAD

**Issue by castilio20** [blay09/CraftingTweaks#216]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.16-beta

### Mod Version

21.0.3

### Balm Version

21.0.6

### Describe the Issue

so when you try to do any right/left click in the inventory it just spam 
![Screenshot_6](https://github.com/TwelveIterationMods/CraftingTweaks/assets/76228548/e210abad-e035-4654-99ad-a7d8b66db15c)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no just balm and crafting tweaks

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm
