### ISSUE TITLE
Server crash when decompressing recursive items

### ISSUE THREAD

**Issue by jasminexs** [blay09/CraftingTweaks#218]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

8.1.9

### Balm Version

N/A

### Describe the Issue

Minecraft 1.12.2
Some items can be crafted into themselves, for instance the crafting station from Tinkers' Construct, or emptying Thermal Expansion tanks. Crafting tweaks sees this as a decompress-able recipe. When I decompress-stack one of these items, I believe the server is infinitely repeating the same crafting operation, crashing it. I would like to be able to keep these recipes, as I find them very useful.
Video: https://streamable.com/djwgov
The only mods used are Crafting Tweaks, Mixin Booter, and Groovy Script to add the custom "decompressing" recipe.
Video link: https://streamable.com/djwgov

### Logs

https://pastebin.com/xgfzPy7E (doesn't say anything useful)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Minecraft 1.12.2 stopped being supported almost six years ago.

**Comment by jasminexs** [comment]
😢
