### ISSUE TITLE
Can't open player list on server

### ISSUE THREAD

**Issue by UnderMan4** [blay09/CraftingTweaks#220]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Loader Version

0.16.0

### Mod Version

21.0.1

### Balm Version

10.3.6

### Describe the Issue

mc version: 20.0.6

Default "Refill Last Stack" keybind is colliding with showing player list on servers.

**Comment by BlayTheNinth** [comment]
Minecraft 1.20.6 is no longer supported. Does this issue still occur in 1.20.1 or 1.21.1?

**Comment by wolfoxcs** [comment]
> Minecraft 1.20.6 is no longer supported. Does this issue still occur in 1.20.1 or 1.21.1?

Yup, the problem is that every key bind conflict with basic key binds. So if I bind "clear grid" to s, then I can't walk backwards etc.
I am playing on 1.21.1 fabric right now.
