### ISSUE TITLE
Items constantly rotate in crafting grid

### ISSUE THREAD

**Issue by GrayPixel47** [blay09/CraftingTweaks#222]
### ~~~ IMPORTANT SECURITY NOTICE ~~~

- [X] Users might post VIRUS LINKS in comment responses to issue reports. **DO NOT DOWNLOAD ANY FILES FROM HERE.**

### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Mod Version

18.2.5

### Balm Version

7.3.9

### Describe the Issue

any item placed in the crafting grid will rapidly spin
[2024-08-27 15-29-42.zip](https://github.com/user-attachments/files/16769397/2024-08-27.15-29-42.zip)

**Comment by BlayTheNinth** [comment]
Cannot reproduce. It sounds like whatever key you have bound to "Rotate Grid" is stuck. Try unbinding the key or restarting your computer / reconnecting your keyboard.
