### ISSUE TITLE
Crafting Tweaks associated with a thread lock that eventually crashes server

### ISSUE THREAD

**Issue by ncottrill** [blay09/CraftingTweaks#224]
### Security Notice

- [X] Users might post VIRUS LINKS in comment responses to issue reports. **DO NOT DOWNLOAD ANY FILES FROM HERE.**

### Minecraft Version

1.21.1

### Mod Loader

NeoForge

### Mod Loader Version

21.1.34

### Mod Version

21.1.2

### Balm Version

21.0.19

### Describe the Issue

This mod is associated with locking up a server thread and then eventually crashing the server. 
The server is running ATM 10.
I will include the crash report.
[crash-2024-09-03_15.59.07-server.txt](https://github.com/user-attachments/files/16858619/crash-2024-09-03_15.59.07-server.txt)

**Comment by ncottrill** [comment]
Still crashing about 5-7 times per 24 hours. Here is another crash log for comparison now that the ATM 10 modpack is on version 10-0.59

[crash-2024-09-28_21.39.52-server.txt](https://github.com/user-attachments/files/17177621/crash-2024-09-28_21.39.52-server.txt)

**Comment by BlayTheNinth** [comment]
Could be related to compressing or decompressing items since that's the only thing that really changed in recent versions

Also reported at https://github.com/AllTheMods/ATM-10/issues/762

**Comment by instinxx** [comment]
https://mclo.gs/CO1nbWW

Same issue still occurs. This is using ATM 10, ver 1.8.

**Comment by BlayTheNinth** [comment]
This should be fixed in v21.1.3 and v21.3.2.

However, to find the actual root cause, please check your log for "Something went wrong trying to refill recipe" some time after updating (which should happen instead of the crash now) and comment here so I can find out what recipe was causing it and put in a more proper fix.
