### ISSUE TITLE
Reminder to cherry-pick translations to 1.20.1/1.21.2

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CraftingTweaks#229]
> If you currently support only the 3 versions you mentioned, may I ask you to cherry-pick the commit from this pull request and apply it to the other 2 branches?

_Originally posted by @Greg-21 in https://github.com/TwelveIterationMods/CraftingTweaks/issues/228#issuecomment-2426993160_

**Comment by Greg-21** [comment]
Thank you! That's exactly what I needed.
