### ISSUE TITLE
"This server does not have crafting tweaks installed." -- 1.7.10 / 1.0.88

### ISSUE THREAD

**Issue by reallydrained** [blay09/CraftingTweaks#234]
### Minecraft Version

1.7.10

### Mod Loader

Forge

### Mod Version

1.0.88 (mc 1.7.10)

### Describe the Issue

When creating a new world the message **"This server does not have crafting tweaks installed. Functionality may be limited."** pops up in the chat after loading in. I am not even playing on a server, this is singleplayer. This didn't used to happen but as my modpack has gotten bigger this message now usually pops up. It doesn't always come up weirdly but usually it does. I have a list of the mods I've added since this started happening so it might be an interaction between mods. If there is any way to disable this message completely that would be really nice. Nothing seems to be broken, it's just the message that's kind of annoying and I'd like to get rid of it.

### Logs

https://mclo.gs/d9heZd1
=

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

[Aneglica](https://github.com/GTNewHorizons/Angelica), [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge), [BugTorch](https://github.com/jss2a98aj/BugTorch)

**Comment by BlayTheNinth** [comment]
Minecraft 1.7.10 is 10+ years old and no longer supported.
