### ISSUE TITLE
Console Spam due to missing mods

### ISSUE THREAD

**Issue by demon-goxa** [blay09/CraftingTweaks#34]
Something Wrong with Industrial Craft 2 and Crafting Tweaks. See in log after 787 line.
Log
-----------
[![Log](https://octodex.github.com/images/yaktocat.png)](http://paste.ee/p/38OcE#)

**Comment by blay09** [comment]
It's complaining about Applied Energistics (among others), which I assume you don't have installed. I might have messed up the isModLoaded() check in the latest version, I guess. It should only spam the log a little though and still function correctly.

**Comment by demon-goxa** [comment]
With the game there is no problem, but I think it's better to get rid of this error in the log as cuts my eyes)

**Comment by blay09** [comment]
Of course, I wasn't planning on keeping the error around.
