### ISSUE TITLE
Add support for Ewy's Workshop

### ISSUE THREAD

**Issue by BakermanLP** [blay09/CraftingTweaks#45]
Hello,
can you please add support for Ewy's Workshop, what should be similar to Steves Workshop?

That would be great.

Thanks in advance
Michael (aka BakermanLP)

**Comment by blay09** [comment]
@EwyBoy was working on adding support, I don't know what happened next.

**Comment by EwyBoy** [comment]
Hahha, I am sorry. I ran into some problems and kinda gave up without looking to much into it.

**Comment by BlayTheNinth** [comment]
I can PR it for you if you'd like.

**Comment by EwyBoy** [comment]
Yes please!
