### ISSUE TITLE
Transfer-to-grid crash [1.0.57]

### ISSUE THREAD

**Issue by dirtyfargo** [blay09/CraftingTweaks#46]
Description: When attempting the recently added 'transfer-to-grid' (W + Shift Click) feature in a portable crafting table from CraftingCraft, I crash out of my world and into the main menu.
I didn't receive an actual crash report as my game was only exited to the main menu. Here is the relevant area of the client log:
https://gist.github.com/dirtyfargo/e46727378a6953876dee
Version: 1.0.57
Forge Version: 10.13.4.1614
CraftingCraft Version: 1.0.7

**Comment by BlayTheNinth** [comment]
Yeah, I need to update CraftingCraft to the latest API still. :p

**Comment by dirtyfargo** [comment]
Ahh that makes sense :P :)

**Comment by dirtyfargo** [comment]
Is craftingcraft still waiting on an API update? I'm getting a crash when I look up a recipe by hovering over an item in my inventory and pressing 'r'  while  the craftingcraft gui is open, and it's mentioning craftingtweaks. :) I am on a server, which doesn't have craftingtweaks installed, and it is just my client crashing. I am also on the latest version of craftingtweaks/craftingcraft.
Crash Report: https://gist.github.com/dirtyfargo/d8ae6aa36d9b85ac8119

**Comment by BlayTheNinth** [comment]
See #69, due to me backporting features from 1.8.9 I had to break the API again. A fixed version of CraftingCraft will be up in an hour or so.

**Comment by dirtyfargo** [comment]
Oh alright awesome sounds good sorry that I didn't see that :)
