### ISSUE TITLE
1.8 Mods Support

### ISSUE THREAD

**Issue by WenXin20** [blay09/CraftingTweaks#48]
Can you add mod support for the NeoTech Mod Duel Crafting Table,  the Progressive Automation Mod Crafters, and the Storage Silo Mod Crafting Silo? Thanks

**Comment by BlayTheNinth** [comment]
I've just implemented a new IMC API that makes it super easy for mods to add support. I will no longer be adding support on my side unless it's absolutely unavoidable. That way things are going to continue working even if the other mods change their internal names and such.

Feel free to ask the respective mod devs about adding support and link them to the IMC API documentation at:
https://github.com/blay09/CraftingTweaks/blob/mc189/README.md

**Comment by BlayTheNinth** [comment]
On second thought, I may create a separate project called CraftingTweaks Addons that adds support for the time being.

**Comment by WenXin20** [comment]
Ok, cool & thanks for your time

**Comment by BlayTheNinth** [comment]
http://minecraft.curseforge.com/projects/craftingtweaks-addons

Not touching NeoTech, because Scala.

**Comment by WenXin20** [comment]
Ok, thanks
