### ISSUE TITLE
Still Crashing when using W+click 

### ISSUE THREAD

**Issue by chitown3** [blay09/CraftingTweaks#49]
Pressing w + click an item into your portable crafting table casues a crash with the latest versions of this mod. It does not crash when doing so in a vanilla crafting bench.  http://pastebin.com/FkWFeNTg

I also lost some items when doing this but I cannot reproduce. I lost a resonant jet pack and some fluxducts. Luckily I'm in sp so I just spawned them back in

**Comment by BlayTheNinth** [comment]
Did you update CraftingCraft as well?

**Comment by chitown3** [comment]
Yes I did and also have the lastest trashslot 1.0.31 installed 
http://i.imgur.com/SMVSORJ.png

Edit: Do you think it could be trashslot causing my items to disappear somehow?

**Comment by BlayTheNinth** [comment]
Ah. There's a newer version for CraftingCraft but I forgot to upload it to CurseForge. It should be up in a bit (http://jenkins.blay09.net/job/CraftingCraft%201.7.10/lastSuccessfulBuild/).

TrashSlot never deletes items unless they're replaced by another item within the trash slot. So as long as you don't use the trash slot for storage or randomly click the delete key on items, there should be no problem.

**Comment by chitown3** [comment]
That fixed the crashing. Thanks!  I'll close this for now
