### ISSUE TITLE
"This server does not have crafting tweaks installed"

### ISSUE THREAD

**Issue by RaineAndrews** [blay09/CraftingTweaks#65]
I have crafting tweaks installed on the server, but players get this message regardless.  Is there something special that has to be done in order for crafting tweaks to flag that it is installed?

**Comment by BlayTheNinth** [comment]
Huh. Is the Crafting Tweaks on the server & clients updated to the latest version?
Are they running on a super slow connection? The message should only appear if the server didn't reply to the clent's hello-message within ten seconds.

Is this on 1.7.10 or 1.8.9?

**Comment by RaineAndrews** [comment]
1.8.9 on 3.0.52

**Comment by RaineAndrews** [comment]
I think it might be an issue with the server.  Hold off on troubleshooting until I'm certain it's a crafting tweaks issue

**Comment by RaineAndrews** [comment]
Server related issue.
