### ISSUE TITLE
"Soft" Crash

### ISSUE THREAD

**Issue by Fortist** [blay09/CraftingTweaks#69]
When Rotating a certain recipe, my world crashed and sent me back to the main menu. 
(The recipe was to make an Enhanced Inventory Chest, but the recipe was wrong anyway, regardless if I rotated it.)
When I tried to spread out Tcon's stone tool rods with the new spread option, it did the same as above.
Otherwise, the spreading option works fine, as far as Ive used it.
Both times I was using your CraftingCraft's portable crafting table.

I think Ive found a chunk of log.
http://pastebin.com/Pecuniqb

**Comment by BlayTheNinth** [comment]
Right, the latest version has an API change and I forgot to update CraftingCraft again. :) Will be putting up a fix later today.

**Comment by Fortist** [comment]
Awesome.

**Comment by BlayTheNinth** [comment]
Update is on CurseForge now.

**Comment by Fortist** [comment]
It seems there are two folders within Craftingcraft
One is "Craftingcraft" the other is "Craftcraft"
And theres a crash referencing Craftcraft about a missing class.

**Comment by BlayTheNinth** [comment]
You forgot to post the log to the crash you're mentioning.

**Comment by Fortist** [comment]
Well, I already told you the problem.
Theres two folders within the mod file, with the same files in it, I think. One probably being an older or newer version. (Ie, you have the 1.8.9 and 1.7.10 mods in the same .jar)
Deleting craftcraft fixed the issue.

**Comment by BlayTheNinth** [comment]
"There are two folders within CraftingCraft"
"There's a crash about a missing class"
...
"I told you the problem"

Next time I ask for a log, instead of arguing, provide a log. It's that simple and as a result won't upset the poor mod developer.

http://minecraft.curseforge.com/projects/craftingcraft/files/2285991 once approved

**Comment by Fortist** [comment]
I wasnt arguing, I wasnt asking for a fix, Im telling you something is wrong. It takes a few seconds to just go and look yourself.
Maybe I should have clarified I fixed it myself by just deleting the folder.
I also should have clarified where in the folder structure it was.
Oh fucking well.
