### ISSUE TITLE
Crash with waila craftingtweaks-mc1.7.10-1.0.79

### ISSUE THREAD

**Issue by b0bst3r** [blay09/CraftingTweaks#76]
If you go into Waila settings and set to default you get this crash when coming back out of the settings pages.

http://pastebin.com/05wCJye1

**Comment by b0bst3r** [comment]
Fixed by rolling back to previous version

**Comment by StoneLegion** [comment]
Also having the same issue 2 diff people:
http://pastebin.com/n5H3wzyP
http://pastebin.com/iVWY8Sfv
