### ISSUE TITLE
[1.9.4] Incorrect version

### ISSUE THREAD

**Issue by HendrikJ79** [blay09/CraftingTweaks#92]
Maybe a mistake, but you put a 1.10.2 version on 1.9.4?

[Log](https://gist.github.com/HendrikJ79/165cedac4cb0d3c3380a5d9c2531934c)
[Picture](http://imgur.com/a/ybOUX)

**Comment by BlayTheNinth** [comment]
Yeah, I did it the wrong way around so it wasn't compatible even though it technically would be, and couldn't be bothered to unmark the old versions as 1.9.4 yet. The listing should be correct now.
