### ISSUE TITLE
[Request] JACB-Support

### ISSUE THREAD

**Issue by Rsge** [blay09/CraftingTweaks#95]
Hello,

could you please add support for the JACB (Just Another Crafting Bench) mod by VanhalMinecraft?

Thanks : )

**Comment by BlayTheNinth** [comment]
Doesn't feel worth it to release a new version just for this, but you can get it [from my Jenkins](http://jenkins.blay09.net/job/Crafting%20Tweaks%201.10/lastSuccessfulBuild/) if you even still need it.
